- src/test/kotlin/com/pestphp/pest/tests/PestLightCodeFixture.kt
- src/test/kotlin/com/pestphp/pest/tests/types/ThisTypingTest.kt
- src/test/kotlin/com/pestphp/pest/tests/types/fixtures/TestCase.php
- src/test/kotlin/com/pestphp/pest/tests/types/fixtures/this/itTest.txt
- src/test/kotlin/com/pestphp/pest/tests/types/fixtures/this/testTest.txt
I made PHP files with `txt` extension because `<caret>` is illegal PHP syntax and there were errors
> #13 create functional tests

- README.md
> Add EAP install guide to the README

- README.md
Added description to setup Local Pest Integration settings.
issues: #...
> Update README.md to include Local Pest

- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/pestphp/pest/configuration/PestRunConfigurationHandler.kt
> fix(runner): Fixed running with dataset

- CHANGELOG.md
- src/main/kotlin/com/pestphp/pest/PestFrameworkType.kt
- src/main/kotlin/com/pestphp/pest/configuration/PestVersionDetector.kt
- src/test/kotlin/com/pestphp/pest/tests/PestLightCodeFixture.kt
This pr adds the pest version in the pest settings.
> feat(runner): Add pest version in runner settings

- CHANGELOG.md
- src/main/kotlin/com/pestphp/pest/configuration/PestRunConfiguration.kt
- src/main/kotlin/com/pestphp/pest/types/ThisTypeProvider.kt
- src/test/kotlin/com/pestphp/pest/tests/types/FunctionTypeTest.kt
- src/test/kotlin/com/pestphp/pest/tests/types/fixtures/function/testTest.php
> Test functions type provider

- CHANGELOG.md
- src/main/kotlin/com/pestphp/pest/GithubErrorReporter.kt
- src/main/resources/META-INF/plugin.xml
> feat(report): Add error reporting to GitHub

- CHANGELOG.md
- src/main/kotlin/com/pestphp/pest/PestFunctionsUtil.kt
- src/main/kotlin/com/pestphp/pest/inspections/DuplicateTestNameInspection.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/inspectionDescriptions/DuplicateTestNameInspection.html
- src/test/kotlin/com/pestphp/pest/inspections/DuplicateTestNameInspectionTest.kt
- src/test/resources/com/pestphp/pest/inspections/DuplicateTestName.php
- src/test/resources/com/pestphp/pest/inspections/NoDuplicateTestName.php
> feat(inspection): Add duplicate test name inspection

- CHANGELOG.md
- src/main/kotlin/com/pestphp/pest/GithubErrorReporter.kt
- src/main/kotlin/com/pestphp/pest/inspections/DuplicateTestNameInspection.kt
> fix(inspection): Fixed duplicate test inspection when no name on the test yet

- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/pestphp/pest/PestUtil.kt
- src/test/kotlin/com/pestphp/pest/PestUtil/IsPestTestFileTest.kt
- src/test/kotlin/com/pestphp/pest/inspections/DuplicateTestNameInspectionTest.kt
- src/test/kotlin/com/pestphp/pest/tests/types/BaseTypeTest.kt
- src/test/kotlin/com/pestphp/pest/tests/types/FunctionTypeTest.kt
- src/test/kotlin/com/pestphp/pest/tests/types/ThisFieldTypeTest.kt
- src/test/kotlin/com/pestphp/pest/tests/types/ThisTypeTest.kt
- src/test/resources/com/pestphp/pest/PestUtil/PestTestFunctionCallWithNamesapce.php
> fix(runner): Fix finding tests in namespace

- CHANGELOG.md
- src/main/kotlin/com/pestphp/pest/configuration/PestLocationProvider.kt
> fix(location-provider): Allow location to be null

- CHANGELOG.md
- detekt-config.yml
- src/main/kotlin/com/pestphp/pest/PestFunctionsUtil.kt
- src/main/kotlin/com/pestphp/pest/configuration/PestLocationProvider.kt
- src/main/kotlin/com/pestphp/pest/configuration/PestRerunFailedTestsAction.kt
- src/main/kotlin/com/pestphp/pest/runner/PestConsoleProperties.kt
- src/test/kotlin/com/pestphp/pest/PestUtil/GetPestTestsTest.kt
> fix(rerun): Fix rerunning test in namespace

- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/pestphp/pest/GithubErrorReporter.kt
- src/main/kotlin/com/pestphp/pest/configuration/PestRunConfiguration.kt
- src/main/kotlin/com/pestphp/pest/configuration/PestRunConfigurationProducer.kt
- src/main/kotlin/com/pestphp/pest/configuration/PestRunConfigurationSettings.kt
- src/main/kotlin/com/pestphp/pest/configuration/PestRunnerSettings.kt
- src/main/kotlin/com/pestphp/pest/configuration/PestTestRunConfigurationEditor.kt
- src/main/kotlin/com/pestphp/pest/configuration/PestVersionDetector.kt
- src/main/kotlin/com/pestphp/pest/coverage/PestCoverageProgramRunner.kt
- src/main/kotlin/com/pestphp/pest/runner/PestConsoleProperties.kt
- src/test/kotlin/com/pestphp/pest/configuration/PestRunConfigurationTest.kt
- src/test/kotlin/com/pestphp/pest/tests/PestLightCodeFixture.kt
- src/test/resources/com/pestphp/pest/configuration/FileWithPestTest.php
- src/test/resources/com/pestphp/pest/goto/PestTestFinder/test/App/UserTest.php
This pull request adds support for the pcov coverage engine
issues: #42
> feat(runner): Add pcov engine support

- .github/workflows/build.yml
- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/pestphp/pest/PestFunctionsUtil.kt
- src/main/kotlin/com/pestphp/pest/PestNamingUtil.kt
- src/main/kotlin/com/pestphp/pest/configuration/PestRerunFailedTestsAction.kt
- src/main/kotlin/com/pestphp/pest/configuration/PestRunConfiguration.kt
- src/main/kotlin/com/pestphp/pest/configuration/PestRunConfigurationHandler.kt
- src/main/kotlin/com/pestphp/pest/notifications/OutdatedNotification.kt
- src/main/resources/pestBundle.properties
- src/test/kotlin/com/pestphp/pest/PestUtil/GetPestTestNameTests.kt
- src/test/kotlin/com/pestphp/pest/PestUtil/ToPestTestRegexTests.kt
- src/test/kotlin/com/pestphp/pest/tests/PestUtil/PestUtilTest.kt
> feat(runner): Add rerunning support

- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/pestphp/pest/PestFrameworkType.kt
- src/main/kotlin/com/pestphp/pest/PestNamingUtil.kt
- src/main/kotlin/com/pestphp/pest/configuration/PestRunConfiguration.kt
- src/main/kotlin/com/pestphp/pest/configuration/PestRunConfigurationHandler.kt
- src/main/kotlin/com/pestphp/pest/configuration/PestVersionDetector.kt
- src/test/kotlin/com/pestphp/pest/PestUtil/GetPestTestNameTests.kt
- src/test/kotlin/com/pestphp/pest/configuration/PestRunConfigurationTest.kt
- src/test/kotlin/com/pestphp/pest/tests/PestUtil/PestUtilTest.kt
> feat(path-mapping): Add path mapping support

- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/pestphp/pest/inspections/SuppressExpressionResultUnusedInspection.kt
- src/main/resources/META-INF/plugin.xml
> fix(inspection): Suppress result unused when in Pest tests

- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/pestphp/pest/GithubErrorReporter.kt
- src/main/kotlin/com/pestphp/pest/PestTestFileUtil.kt
- src/test/kotlin/com/pestphp/pest/configuration/PestConfigurationFileTest.kt
> fix(2021.1): Add support for PS-2021.1

- CHANGELOG.md
- src/main/kotlin/com/pestphp/pest/PestNamingUtil.kt
- src/test/kotlin/com/pestphp/pest/pestUtil/ToPestTestRegexTests.kt
- src/test/resources/com/pestphp/pest/PestUtil/PestTestFunctionCallWithCircumflex.php
> fix(naming): Escape ^ characters

- src/main/kotlin/com/pestphp/pest/PestIconProvider.kt
- src/main/kotlin/com/pestphp/pest/PestUtil.kt
> fix(error): Fix exception from pest test file

- CHANGELOG.md
- art/icons/dataset@dark.svg
- art/icons/dataset@light.svg
> feat: added new dataset icons

- .run/Run IDE with Plugin.run.xml
- .run/Run Plugin Tests.run.xml
- .run/Run Plugin Verification.run.xml
- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- src/main/kotlin/com/pestphp/pest/GithubErrorReporter.kt
- src/main/kotlin/com/pestphp/pest/PestNamingUtil.kt
- src/main/kotlin/com/pestphp/pest/PestTestRunLineMarkerProvider.kt
- src/main/kotlin/com/pestphp/pest/PestUtil.kt
- src/main/kotlin/com/pestphp/pest/configuration/PestRunConfiguration.kt
- src/test/kotlin/com/pestphp/pest/PestTestRunLineMarkerProviderTest.kt
- src/test/kotlin/com/pestphp/pest/pestUtil/ToPestFqnTests.kt
Adds icons based on if the test is passing or not.
issues: #89
> feat(state): Add test state icons

- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/pestphp/pest/PestIcons.kt
- src/main/kotlin/com/pestphp/pest/PestTestRunLineMarkerProvider.kt
- src/main/kotlin/com/pestphp/pest/configuration/PestRunConfiguration.kt
- src/main/kotlin/com/pestphp/pest/configuration/PestRunConfigurationProducer.kt
- src/test/kotlin/com/pestphp/pest/PestTestRunLineMarkerProviderTest.kt
> feat(run): Add run all on top of file

- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/pestphp/pest/goto/PestTestGoToSymbolContributor.kt
- src/main/kotlin/com/pestphp/pest/indexers/PestTestIndex.kt
- src/main/kotlin/com/pestphp/pest/structureView/PestStructureViewElement.kt
- src/main/resources/META-INF/plugin.xml
> feat(search): Add symbol contributor for pest test

- CHANGELOG.md
- src/main/kotlin/com/pestphp/pest/PestIconProvider.kt
- src/main/kotlin/com/pestphp/pest/fileListeners/ExtendAsyncFileListener.kt
- src/main/kotlin/com/pestphp/pest/generators/ExpectationGenerator.kt
- src/main/kotlin/com/pestphp/pest/services/ExpectationFileService.kt
- src/test/kotlin/com/pestphp/pest/generators/ExpectationGeneratorTest.kt
Ignore exceptions happening because of out of date stubs.
Resolves #152
resolves: #152 
resolves: #150 
resolves: #148 
resolves: #130
> fix(file-listener): fix different bugs related to the file listener

- CHANGELOG.md
- src/main/kotlin/com/pestphp/pest/goto/PestTestGoToSymbolContributor.kt
> Change decorator to interface implementation instead

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/run-ui-tests.yml
- build.gradle.kts
> chore(build): Update build process

- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/pestphp/pest/customExpectations/ExpectationFileService.kt
- src/main/kotlin/com/pestphp/pest/parser/PestConfigurationFileParser.kt
- src/main/kotlin/com/pestphp/pest/snapshotTesting/SnapshotLineMarkerProvider.kt
- src/main/kotlin/com/pestphp/pest/types/ThisTypeProvider.kt
- src/test/kotlin/com/pestphp/pest/configuration/PestConfigurationFileTest.kt
- src/test/kotlin/com/pestphp/pest/snapshotTesting/SnapshotLineMarkerProviderTest.kt
- src/test/resources/com/pestphp/pest/configuration/DIRFeature/FeatureTest.php
- src/test/resources/com/pestphp/pest/configuration/Pest.php
- src/test/resources/com/pestphp/pest/snapshotTesting/snapshotAssertionUseStatement.php
> feat(uses): dir support

- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/pestphp/pest/types/HigherOrderExtendTypeProvider.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/com/pestphp/pest/higherOrderExpectations/HigherOrderExpectationAssertionCompletionTest.kt
- src/test/kotlin/com/pestphp/pest/higherOrderExpectations/HigherOrderExpectationCompletionTest.kt
- src/test/kotlin/com/pestphp/pest/types/ExpectCallCompletionTest.kt
- src/test/resources/com/pestphp/pest/higherOrderExpectations/ExpectMethodAssertionCompletion.php
- src/test/resources/com/pestphp/pest/higherOrderExpectations/ExpectMethodAssertionCompletionChained.php
- src/test/resources/com/pestphp/pest/higherOrderExpectations/ExpectMethodAssertionCompletionChainedAssertions.php
- src/test/resources/com/pestphp/pest/higherOrderExpectations/ExpectMethodCompletion.php
- src/test/resources/com/pestphp/pest/higherOrderExpectations/ExpectMethodCompletionChained.php
- src/test/resources/com/pestphp/pest/higherOrderExpectations/ExpectMethodCompletionChainedAssertions.php
- src/test/resources/com/pestphp/pest/higherOrderExpectations/ExpectPropertyAssertionCompletion.php
- src/test/resources/com/pestphp/pest/higherOrderExpectations/ExpectPropertyAssertionCompletionChained.php
- src/test/resources/com/pestphp/pest/higherOrderExpectations/ExpectPropertyAssertionCompletionChainedAssertions.php
- src/test/resources/com/pestphp/pest/higherOrderExpectations/ExpectPropertyCompletion.php
- src/test/resources/com/pestphp/pest/higherOrderExpectations/ExpectPropertyCompletionChained.php
- src/test/resources/com/pestphp/pest/higherOrderExpectations/ExpectPropertyCompletionChainedAssertions.php
- src/test/resources/com/pestphp/pest/higherOrderExpectations/stubs.php
> feat(higher-order-expectations): Add autocompletion for higher order expectations

- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/pestphp/pest/inspections/DuplicateCustomExpectationInspection.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/com/pestphp/pest/inspections/DuplicateExtendNameInspectionTest.kt
- src/test/resources/com/pestphp/pest/inspections/DuplicateCustomExpectation.php
- src/test/resources/com/pestphp/pest/inspections/NoDuplicateCustomExpectation.php
> feat(inspection): Check for duplicate custom expectation check

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- settings.gradle.kts
- src/main/kotlin/com/pestphp/pest/inspections/ChangeTestNameCasingQuickFix.kt
- src/main/kotlin/com/pestphp/pest/inspections/InvalidTestNameCaseInspection.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/com/pestphp/pest/inspections/InvalidTestNameCaseInspectionTest.kt
- src/test/resources/com/pestphp/pest/inspections/InvalidTestNameCase.after.php
- src/test/resources/com/pestphp/pest/inspections/InvalidTestNameCase.php
- src/test/resources/com/pestphp/pest/inspections/ValidTestNameCase.php
https://user-images.githubusercontent.com/5870441/168444321-1bb98619-3bc5-4875-b967-be20ee6491cd.mp4
resolves: #162
> Add quickfix for changing the casing of a pest test name

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- src/main/kotlin/com/pestphp/pest/customExpectations/CustomExpectationIndex.kt
- src/main/kotlin/com/pestphp/pest/customExpectations/expectationUtil.kt
- src/main/kotlin/com/pestphp/pest/inspections/ChangeMultipleExpectCallsToChainableQuickFix.kt
- src/main/kotlin/com/pestphp/pest/inspections/DuplicateCustomExpectationInspection.kt
- src/main/kotlin/com/pestphp/pest/inspections/MultipleExpectChainableInspection.kt
- src/main/kotlin/com/pestphp/pest/types/HigherOrderExtendTypeProvider.kt
- src/main/kotlin/com/pestphp/pest/types/ThisExtendTypeProvider.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/com/pestphp/pest/customExpectations/CustomExpectationIndexTest.kt
- src/test/kotlin/com/pestphp/pest/inspections/MultipleExpectChainableInspectionTest.kt
- src/test/resources/com/pestphp/pest/inspections/ExpectCallsWithOtherStatementsBetween.php
- src/test/resources/com/pestphp/pest/inspections/ManyExpectCall.after.php
- src/test/resources/com/pestphp/pest/inspections/ManyExpectCall.php
- src/test/resources/com/pestphp/pest/inspections/MultipleExpectCall.after.php
- src/test/resources/com/pestphp/pest/inspections/MultipleExpectCall.php
- src/test/resources/com/pestphp/pest/inspections/MultipleExpectCallsWithOtherStatementsBetween.after.php
- src/test/resources/com/pestphp/pest/inspections/MultipleExpectCallsWithOtherStatementsBetween.php
- src/test/resources/com/pestphp/pest/inspections/SingleExpectCall.php
> Add inspection/quickfix for multiple expect to and statements

- CHANGELOG.md
- src/main/kotlin/com/pestphp/pest/PestNamingUtil.kt
- src/main/kotlin/com/pestphp/pest/configuration/PestRunConfiguration.kt
Add support for running a single test in pest v2
issues: #...
> feat(pest): Add support for running a single test
